// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status_message.proto

package ca.wise.fgm.proto;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fgm.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The status code.
   * </pre>
   *
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   *A message about the status.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *A message about the status.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
