// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_server.proto

package ca.wise.rpc.proto;

public interface FileResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.FileResult)
    com.google.protobuf.MessageOrBuilder {
}
