// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

public interface CoverageStoreDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoserver.CoverageStoreDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   * @return Whether the coverageStore field is set.
   */
  boolean hasCoverageStore();
  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   * @return The coverageStore.
   */
  ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getCoverageStore();
  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   */
  ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder getCoverageStoreOrBuilder();
}
