// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

/**
 * Protobuf type {@code geoserver.CoverageStoreDetails}
 */
public final class CoverageStoreDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geoserver.CoverageStoreDetails)
    CoverageStoreDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoverageStoreDetails.newBuilder() to construct.
  private CoverageStoreDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoverageStoreDetails() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CoverageStoreDetails();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CoverageStoreDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder subBuilder = null;
            if (coverageStore_ != null) {
              subBuilder = coverageStore_.toBuilder();
            }
            coverageStore_ = input.readMessage(ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coverageStore_);
              coverageStore_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.geoserver.proto.CoverageStoreDetails.class, ca.wise.geoserver.proto.CoverageStoreDetails.Builder.class);
  }

  public interface CoverageStoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geoserver.CoverageStoreDetails.CoverageStore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     * @return The description.
     */
    com.google.protobuf.StringValue getDescription();
    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     */
    com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();

    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     * @return The type.
     */
    com.google.protobuf.StringValue getType();
    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getTypeOrBuilder();

    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     * @return Whether the enabled field is set.
     */
    boolean hasEnabled();
    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     * @return The enabled.
     */
    com.google.protobuf.BoolValue getEnabled();
    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     */
    com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder();

    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     * @return Whether the workspace field is set.
     */
    boolean hasWorkspace();
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     * @return The workspace.
     */
    ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace();
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     */
    ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder();

    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     * @return Whether the default field is set.
     */
    boolean hasDefault();
    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     * @return The default.
     */
    com.google.protobuf.BoolValue getDefault();
    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     */
    com.google.protobuf.BoolValueOrBuilder getDefaultOrBuilder();

    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     * @return The url.
     */
    com.google.protobuf.StringValue getUrl();
    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     */
    com.google.protobuf.StringValueOrBuilder getUrlOrBuilder();

    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     * @return Whether the coverages field is set.
     */
    boolean hasCoverages();
    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     * @return The coverages.
     */
    com.google.protobuf.StringValue getCoverages();
    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     */
    com.google.protobuf.StringValueOrBuilder getCoveragesOrBuilder();
  }
  /**
   * Protobuf type {@code geoserver.CoverageStoreDetails.CoverageStore}
   */
  public static final class CoverageStore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geoserver.CoverageStoreDetails.CoverageStore)
      CoverageStoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CoverageStore.newBuilder() to construct.
    private CoverageStore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CoverageStore() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CoverageStore();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CoverageStore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (description_ != null) {
                subBuilder = description_.toBuilder();
              }
              description_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(description_);
                description_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (type_ != null) {
                subBuilder = type_.toBuilder();
              }
              type_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(type_);
                type_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (enabled_ != null) {
                subBuilder = enabled_.toBuilder();
              }
              enabled_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enabled_);
                enabled_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder subBuilder = null;
              if (workspace_ != null) {
                subBuilder = workspace_.toBuilder();
              }
              workspace_ = input.readMessage(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(workspace_);
                workspace_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (Default_ != null) {
                subBuilder = Default_.toBuilder();
              }
              Default_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Default_);
                Default_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (url_ != null) {
                subBuilder = url_.toBuilder();
              }
              url_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(url_);
                url_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (coverages_ != null) {
                subBuilder = coverages_.toBuilder();
              }
              coverages_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coverages_);
                coverages_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_CoverageStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.class, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue description_;
    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return description_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getDescription() {
      return description_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : description_;
    }
    /**
     * <code>.google.protobuf.StringValue description = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder() {
      return getDescription();
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue type_;
    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return type_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getType() {
      return type_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : type_;
    }
    /**
     * <code>.google.protobuf.StringValue type = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getTypeOrBuilder() {
      return getType();
    }

    public static final int ENABLED_FIELD_NUMBER = 4;
    private com.google.protobuf.BoolValue enabled_;
    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     * @return Whether the enabled field is set.
     */
    @java.lang.Override
    public boolean hasEnabled() {
      return enabled_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public com.google.protobuf.BoolValue getEnabled() {
      return enabled_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
    }
    /**
     * <code>.google.protobuf.BoolValue enabled = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder() {
      return getEnabled();
    }

    public static final int WORKSPACE_FIELD_NUMBER = 5;
    private ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails workspace_;
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     * @return Whether the workspace field is set.
     */
    @java.lang.Override
    public boolean hasWorkspace() {
      return workspace_ != null;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     * @return The workspace.
     */
    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace() {
      return workspace_ == null ? ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance() : workspace_;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
     */
    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder() {
      return getWorkspace();
    }

    public static final int _DEFAULT_FIELD_NUMBER = 6;
    private com.google.protobuf.BoolValue Default_;
    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     * @return Whether the default field is set.
     */
    @java.lang.Override
    public boolean hasDefault() {
      return Default_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     * @return The default.
     */
    @java.lang.Override
    public com.google.protobuf.BoolValue getDefault() {
      return Default_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : Default_;
    }
    /**
     * <code>.google.protobuf.BoolValue _default = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.BoolValueOrBuilder getDefaultOrBuilder() {
      return getDefault();
    }

    public static final int URL_FIELD_NUMBER = 7;
    private com.google.protobuf.StringValue url_;
    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return url_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     * @return The url.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getUrl() {
      return url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : url_;
    }
    /**
     * <code>.google.protobuf.StringValue url = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getUrlOrBuilder() {
      return getUrl();
    }

    public static final int COVERAGES_FIELD_NUMBER = 8;
    private com.google.protobuf.StringValue coverages_;
    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     * @return Whether the coverages field is set.
     */
    @java.lang.Override
    public boolean hasCoverages() {
      return coverages_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     * @return The coverages.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getCoverages() {
      return coverages_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : coverages_;
    }
    /**
     * <code>.google.protobuf.StringValue coverages = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getCoveragesOrBuilder() {
      return getCoverages();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (description_ != null) {
        output.writeMessage(2, getDescription());
      }
      if (type_ != null) {
        output.writeMessage(3, getType());
      }
      if (enabled_ != null) {
        output.writeMessage(4, getEnabled());
      }
      if (workspace_ != null) {
        output.writeMessage(5, getWorkspace());
      }
      if (Default_ != null) {
        output.writeMessage(6, getDefault());
      }
      if (url_ != null) {
        output.writeMessage(7, getUrl());
      }
      if (coverages_ != null) {
        output.writeMessage(8, getCoverages());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (description_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDescription());
      }
      if (type_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getType());
      }
      if (enabled_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEnabled());
      }
      if (workspace_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getWorkspace());
      }
      if (Default_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDefault());
      }
      if (url_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getUrl());
      }
      if (coverages_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getCoverages());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore)) {
        return super.equals(obj);
      }
      ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore other = (ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasEnabled() != other.hasEnabled()) return false;
      if (hasEnabled()) {
        if (!getEnabled()
            .equals(other.getEnabled())) return false;
      }
      if (hasWorkspace() != other.hasWorkspace()) return false;
      if (hasWorkspace()) {
        if (!getWorkspace()
            .equals(other.getWorkspace())) return false;
      }
      if (hasDefault() != other.hasDefault()) return false;
      if (hasDefault()) {
        if (!getDefault()
            .equals(other.getDefault())) return false;
      }
      if (hasUrl() != other.hasUrl()) return false;
      if (hasUrl()) {
        if (!getUrl()
            .equals(other.getUrl())) return false;
      }
      if (hasCoverages() != other.hasCoverages()) return false;
      if (hasCoverages()) {
        if (!getCoverages()
            .equals(other.getCoverages())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasEnabled()) {
        hash = (37 * hash) + ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + getEnabled().hashCode();
      }
      if (hasWorkspace()) {
        hash = (37 * hash) + WORKSPACE_FIELD_NUMBER;
        hash = (53 * hash) + getWorkspace().hashCode();
      }
      if (hasDefault()) {
        hash = (37 * hash) + _DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + getDefault().hashCode();
      }
      if (hasUrl()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
      }
      if (hasCoverages()) {
        hash = (37 * hash) + COVERAGES_FIELD_NUMBER;
        hash = (53 * hash) + getCoverages().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geoserver.CoverageStoreDetails.CoverageStore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geoserver.CoverageStoreDetails.CoverageStore)
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_CoverageStore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.class, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder.class);
      }

      // Construct using ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (descriptionBuilder_ == null) {
          description_ = null;
        } else {
          description_ = null;
          descriptionBuilder_ = null;
        }
        if (typeBuilder_ == null) {
          type_ = null;
        } else {
          type_ = null;
          typeBuilder_ = null;
        }
        if (enabledBuilder_ == null) {
          enabled_ = null;
        } else {
          enabled_ = null;
          enabledBuilder_ = null;
        }
        if (workspaceBuilder_ == null) {
          workspace_ = null;
        } else {
          workspace_ = null;
          workspaceBuilder_ = null;
        }
        if (DefaultBuilder_ == null) {
          Default_ = null;
        } else {
          Default_ = null;
          DefaultBuilder_ = null;
        }
        if (urlBuilder_ == null) {
          url_ = null;
        } else {
          url_ = null;
          urlBuilder_ = null;
        }
        if (coveragesBuilder_ == null) {
          coverages_ = null;
        } else {
          coverages_ = null;
          coveragesBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getDefaultInstanceForType() {
        return ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore build() {
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore buildPartial() {
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore result = new ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore(this);
        result.name_ = name_;
        if (descriptionBuilder_ == null) {
          result.description_ = description_;
        } else {
          result.description_ = descriptionBuilder_.build();
        }
        if (typeBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        if (enabledBuilder_ == null) {
          result.enabled_ = enabled_;
        } else {
          result.enabled_ = enabledBuilder_.build();
        }
        if (workspaceBuilder_ == null) {
          result.workspace_ = workspace_;
        } else {
          result.workspace_ = workspaceBuilder_.build();
        }
        if (DefaultBuilder_ == null) {
          result.Default_ = Default_;
        } else {
          result.Default_ = DefaultBuilder_.build();
        }
        if (urlBuilder_ == null) {
          result.url_ = url_;
        } else {
          result.url_ = urlBuilder_.build();
        }
        if (coveragesBuilder_ == null) {
          result.coverages_ = coverages_;
        } else {
          result.coverages_ = coveragesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore) {
          return mergeFrom((ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore other) {
        if (other == ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDescription()) {
          mergeDescription(other.getDescription());
        }
        if (other.hasType()) {
          mergeType(other.getType());
        }
        if (other.hasEnabled()) {
          mergeEnabled(other.getEnabled());
        }
        if (other.hasWorkspace()) {
          mergeWorkspace(other.getWorkspace());
        }
        if (other.hasDefault()) {
          mergeDefault(other.getDefault());
        }
        if (other.hasUrl()) {
          mergeUrl(other.getUrl());
        }
        if (other.hasCoverages()) {
          mergeCoverages(other.getCoverages());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue description_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> descriptionBuilder_;
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return descriptionBuilder_ != null || description_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       * @return The description.
       */
      public com.google.protobuf.StringValue getDescription() {
        if (descriptionBuilder_ == null) {
          return description_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : description_;
        } else {
          return descriptionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public Builder setDescription(com.google.protobuf.StringValue value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          description_ = value;
          onChanged();
        } else {
          descriptionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public Builder setDescription(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          description_ = builderForValue.build();
          onChanged();
        } else {
          descriptionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public Builder mergeDescription(com.google.protobuf.StringValue value) {
        if (descriptionBuilder_ == null) {
          if (description_ != null) {
            description_ =
              com.google.protobuf.StringValue.newBuilder(description_).mergeFrom(value).buildPartial();
          } else {
            description_ = value;
          }
          onChanged();
        } else {
          descriptionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public Builder clearDescription() {
        if (descriptionBuilder_ == null) {
          description_ = null;
          onChanged();
        } else {
          description_ = null;
          descriptionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public com.google.protobuf.StringValue.Builder getDescriptionBuilder() {
        
        onChanged();
        return getDescriptionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder() {
        if (descriptionBuilder_ != null) {
          return descriptionBuilder_.getMessageOrBuilder();
        } else {
          return description_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : description_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue description = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getDescriptionFieldBuilder() {
        if (descriptionBuilder_ == null) {
          descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getDescription(),
                  getParentForChildren(),
                  isClean());
          description_ = null;
        }
        return descriptionBuilder_;
      }

      private com.google.protobuf.StringValue type_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> typeBuilder_;
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return typeBuilder_ != null || type_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       * @return The type.
       */
      public com.google.protobuf.StringValue getType() {
        if (typeBuilder_ == null) {
          return type_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : type_;
        } else {
          return typeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public Builder setType(com.google.protobuf.StringValue value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public Builder setType(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (typeBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public Builder mergeType(com.google.protobuf.StringValue value) {
        if (typeBuilder_ == null) {
          if (type_ != null) {
            type_ =
              com.google.protobuf.StringValue.newBuilder(type_).mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          typeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = null;
          onChanged();
        } else {
          type_ = null;
          typeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getTypeBuilder() {
        
        onChanged();
        return getTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getTypeOrBuilder() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilder();
        } else {
          return type_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : type_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue type = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getType(),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }

      private com.google.protobuf.BoolValue enabled_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> enabledBuilder_;
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       * @return Whether the enabled field is set.
       */
      public boolean hasEnabled() {
        return enabledBuilder_ != null || enabled_ != null;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       * @return The enabled.
       */
      public com.google.protobuf.BoolValue getEnabled() {
        if (enabledBuilder_ == null) {
          return enabled_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
        } else {
          return enabledBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public Builder setEnabled(com.google.protobuf.BoolValue value) {
        if (enabledBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enabled_ = value;
          onChanged();
        } else {
          enabledBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public Builder setEnabled(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        if (enabledBuilder_ == null) {
          enabled_ = builderForValue.build();
          onChanged();
        } else {
          enabledBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public Builder mergeEnabled(com.google.protobuf.BoolValue value) {
        if (enabledBuilder_ == null) {
          if (enabled_ != null) {
            enabled_ =
              com.google.protobuf.BoolValue.newBuilder(enabled_).mergeFrom(value).buildPartial();
          } else {
            enabled_ = value;
          }
          onChanged();
        } else {
          enabledBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public Builder clearEnabled() {
        if (enabledBuilder_ == null) {
          enabled_ = null;
          onChanged();
        } else {
          enabled_ = null;
          enabledBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public com.google.protobuf.BoolValue.Builder getEnabledBuilder() {
        
        onChanged();
        return getEnabledFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      public com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder() {
        if (enabledBuilder_ != null) {
          return enabledBuilder_.getMessageOrBuilder();
        } else {
          return enabled_ == null ?
              com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
        }
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
          getEnabledFieldBuilder() {
        if (enabledBuilder_ == null) {
          enabledBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                  getEnabled(),
                  getParentForChildren(),
                  isClean());
          enabled_ = null;
        }
        return enabledBuilder_;
      }

      private ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails workspace_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> workspaceBuilder_;
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       * @return Whether the workspace field is set.
       */
      public boolean hasWorkspace() {
        return workspaceBuilder_ != null || workspace_ != null;
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       * @return The workspace.
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace() {
        if (workspaceBuilder_ == null) {
          return workspace_ == null ? ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance() : workspace_;
        } else {
          return workspaceBuilder_.getMessage();
        }
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public Builder setWorkspace(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails value) {
        if (workspaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          workspace_ = value;
          onChanged();
        } else {
          workspaceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public Builder setWorkspace(
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder builderForValue) {
        if (workspaceBuilder_ == null) {
          workspace_ = builderForValue.build();
          onChanged();
        } else {
          workspaceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public Builder mergeWorkspace(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails value) {
        if (workspaceBuilder_ == null) {
          if (workspace_ != null) {
            workspace_ =
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.newBuilder(workspace_).mergeFrom(value).buildPartial();
          } else {
            workspace_ = value;
          }
          onChanged();
        } else {
          workspaceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public Builder clearWorkspace() {
        if (workspaceBuilder_ == null) {
          workspace_ = null;
          onChanged();
        } else {
          workspace_ = null;
          workspaceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder getWorkspaceBuilder() {
        
        onChanged();
        return getWorkspaceFieldBuilder().getBuilder();
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder() {
        if (workspaceBuilder_ != null) {
          return workspaceBuilder_.getMessageOrBuilder();
        } else {
          return workspace_ == null ?
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance() : workspace_;
        }
      }
      /**
       * <code>.geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> 
          getWorkspaceFieldBuilder() {
        if (workspaceBuilder_ == null) {
          workspaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder>(
                  getWorkspace(),
                  getParentForChildren(),
                  isClean());
          workspace_ = null;
        }
        return workspaceBuilder_;
      }

      private com.google.protobuf.BoolValue Default_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> DefaultBuilder_;
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       * @return Whether the default field is set.
       */
      public boolean hasDefault() {
        return DefaultBuilder_ != null || Default_ != null;
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       * @return The default.
       */
      public com.google.protobuf.BoolValue getDefault() {
        if (DefaultBuilder_ == null) {
          return Default_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : Default_;
        } else {
          return DefaultBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public Builder setDefault(com.google.protobuf.BoolValue value) {
        if (DefaultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Default_ = value;
          onChanged();
        } else {
          DefaultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public Builder setDefault(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        if (DefaultBuilder_ == null) {
          Default_ = builderForValue.build();
          onChanged();
        } else {
          DefaultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public Builder mergeDefault(com.google.protobuf.BoolValue value) {
        if (DefaultBuilder_ == null) {
          if (Default_ != null) {
            Default_ =
              com.google.protobuf.BoolValue.newBuilder(Default_).mergeFrom(value).buildPartial();
          } else {
            Default_ = value;
          }
          onChanged();
        } else {
          DefaultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public Builder clearDefault() {
        if (DefaultBuilder_ == null) {
          Default_ = null;
          onChanged();
        } else {
          Default_ = null;
          DefaultBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public com.google.protobuf.BoolValue.Builder getDefaultBuilder() {
        
        onChanged();
        return getDefaultFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      public com.google.protobuf.BoolValueOrBuilder getDefaultOrBuilder() {
        if (DefaultBuilder_ != null) {
          return DefaultBuilder_.getMessageOrBuilder();
        } else {
          return Default_ == null ?
              com.google.protobuf.BoolValue.getDefaultInstance() : Default_;
        }
      }
      /**
       * <code>.google.protobuf.BoolValue _default = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
          getDefaultFieldBuilder() {
        if (DefaultBuilder_ == null) {
          DefaultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                  getDefault(),
                  getParentForChildren(),
                  isClean());
          Default_ = null;
        }
        return DefaultBuilder_;
      }

      private com.google.protobuf.StringValue url_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> urlBuilder_;
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       * @return Whether the url field is set.
       */
      public boolean hasUrl() {
        return urlBuilder_ != null || url_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       * @return The url.
       */
      public com.google.protobuf.StringValue getUrl() {
        if (urlBuilder_ == null) {
          return url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : url_;
        } else {
          return urlBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public Builder setUrl(com.google.protobuf.StringValue value) {
        if (urlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          url_ = value;
          onChanged();
        } else {
          urlBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public Builder setUrl(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (urlBuilder_ == null) {
          url_ = builderForValue.build();
          onChanged();
        } else {
          urlBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public Builder mergeUrl(com.google.protobuf.StringValue value) {
        if (urlBuilder_ == null) {
          if (url_ != null) {
            url_ =
              com.google.protobuf.StringValue.newBuilder(url_).mergeFrom(value).buildPartial();
          } else {
            url_ = value;
          }
          onChanged();
        } else {
          urlBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public Builder clearUrl() {
        if (urlBuilder_ == null) {
          url_ = null;
          onChanged();
        } else {
          url_ = null;
          urlBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public com.google.protobuf.StringValue.Builder getUrlBuilder() {
        
        onChanged();
        return getUrlFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getUrlOrBuilder() {
        if (urlBuilder_ != null) {
          return urlBuilder_.getMessageOrBuilder();
        } else {
          return url_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : url_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue url = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getUrlFieldBuilder() {
        if (urlBuilder_ == null) {
          urlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getUrl(),
                  getParentForChildren(),
                  isClean());
          url_ = null;
        }
        return urlBuilder_;
      }

      private com.google.protobuf.StringValue coverages_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> coveragesBuilder_;
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       * @return Whether the coverages field is set.
       */
      public boolean hasCoverages() {
        return coveragesBuilder_ != null || coverages_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       * @return The coverages.
       */
      public com.google.protobuf.StringValue getCoverages() {
        if (coveragesBuilder_ == null) {
          return coverages_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : coverages_;
        } else {
          return coveragesBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public Builder setCoverages(com.google.protobuf.StringValue value) {
        if (coveragesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coverages_ = value;
          onChanged();
        } else {
          coveragesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public Builder setCoverages(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (coveragesBuilder_ == null) {
          coverages_ = builderForValue.build();
          onChanged();
        } else {
          coveragesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public Builder mergeCoverages(com.google.protobuf.StringValue value) {
        if (coveragesBuilder_ == null) {
          if (coverages_ != null) {
            coverages_ =
              com.google.protobuf.StringValue.newBuilder(coverages_).mergeFrom(value).buildPartial();
          } else {
            coverages_ = value;
          }
          onChanged();
        } else {
          coveragesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public Builder clearCoverages() {
        if (coveragesBuilder_ == null) {
          coverages_ = null;
          onChanged();
        } else {
          coverages_ = null;
          coveragesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public com.google.protobuf.StringValue.Builder getCoveragesBuilder() {
        
        onChanged();
        return getCoveragesFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getCoveragesOrBuilder() {
        if (coveragesBuilder_ != null) {
          return coveragesBuilder_.getMessageOrBuilder();
        } else {
          return coverages_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : coverages_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue coverages = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getCoveragesFieldBuilder() {
        if (coveragesBuilder_ == null) {
          coveragesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getCoverages(),
                  getParentForChildren(),
                  isClean());
          coverages_ = null;
        }
        return coveragesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geoserver.CoverageStoreDetails.CoverageStore)
    }

    // @@protoc_insertion_point(class_scope:geoserver.CoverageStoreDetails.CoverageStore)
    private static final ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore();
    }

    public static ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoverageStore>
        PARSER = new com.google.protobuf.AbstractParser<CoverageStore>() {
      @java.lang.Override
      public CoverageStore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoverageStore(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CoverageStore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoverageStore> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int COVERAGESTORE_FIELD_NUMBER = 1;
  private ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore coverageStore_;
  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   * @return Whether the coverageStore field is set.
   */
  @java.lang.Override
  public boolean hasCoverageStore() {
    return coverageStore_ != null;
  }
  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   * @return The coverageStore.
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getCoverageStore() {
    return coverageStore_ == null ? ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.getDefaultInstance() : coverageStore_;
  }
  /**
   * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder getCoverageStoreOrBuilder() {
    return getCoverageStore();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (coverageStore_ != null) {
      output.writeMessage(1, getCoverageStore());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (coverageStore_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCoverageStore());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.geoserver.proto.CoverageStoreDetails)) {
      return super.equals(obj);
    }
    ca.wise.geoserver.proto.CoverageStoreDetails other = (ca.wise.geoserver.proto.CoverageStoreDetails) obj;

    if (hasCoverageStore() != other.hasCoverageStore()) return false;
    if (hasCoverageStore()) {
      if (!getCoverageStore()
          .equals(other.getCoverageStore())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCoverageStore()) {
      hash = (37 * hash) + COVERAGESTORE_FIELD_NUMBER;
      hash = (53 * hash) + getCoverageStore().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.CoverageStoreDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.geoserver.proto.CoverageStoreDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geoserver.CoverageStoreDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geoserver.CoverageStoreDetails)
      ca.wise.geoserver.proto.CoverageStoreDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.CoverageStoreDetails.class, ca.wise.geoserver.proto.CoverageStoreDetails.Builder.class);
    }

    // Construct using ca.wise.geoserver.proto.CoverageStoreDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (coverageStoreBuilder_ == null) {
        coverageStore_ = null;
      } else {
        coverageStore_ = null;
        coverageStoreBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_CoverageStoreDetails_descriptor;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.CoverageStoreDetails getDefaultInstanceForType() {
      return ca.wise.geoserver.proto.CoverageStoreDetails.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.CoverageStoreDetails build() {
      ca.wise.geoserver.proto.CoverageStoreDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.CoverageStoreDetails buildPartial() {
      ca.wise.geoserver.proto.CoverageStoreDetails result = new ca.wise.geoserver.proto.CoverageStoreDetails(this);
      if (coverageStoreBuilder_ == null) {
        result.coverageStore_ = coverageStore_;
      } else {
        result.coverageStore_ = coverageStoreBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.geoserver.proto.CoverageStoreDetails) {
        return mergeFrom((ca.wise.geoserver.proto.CoverageStoreDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.geoserver.proto.CoverageStoreDetails other) {
      if (other == ca.wise.geoserver.proto.CoverageStoreDetails.getDefaultInstance()) return this;
      if (other.hasCoverageStore()) {
        mergeCoverageStore(other.getCoverageStore());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.geoserver.proto.CoverageStoreDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.geoserver.proto.CoverageStoreDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore coverageStore_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder> coverageStoreBuilder_;
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     * @return Whether the coverageStore field is set.
     */
    public boolean hasCoverageStore() {
      return coverageStoreBuilder_ != null || coverageStore_ != null;
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     * @return The coverageStore.
     */
    public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore getCoverageStore() {
      if (coverageStoreBuilder_ == null) {
        return coverageStore_ == null ? ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.getDefaultInstance() : coverageStore_;
      } else {
        return coverageStoreBuilder_.getMessage();
      }
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public Builder setCoverageStore(ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore value) {
      if (coverageStoreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coverageStore_ = value;
        onChanged();
      } else {
        coverageStoreBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public Builder setCoverageStore(
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder builderForValue) {
      if (coverageStoreBuilder_ == null) {
        coverageStore_ = builderForValue.build();
        onChanged();
      } else {
        coverageStoreBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public Builder mergeCoverageStore(ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore value) {
      if (coverageStoreBuilder_ == null) {
        if (coverageStore_ != null) {
          coverageStore_ =
            ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.newBuilder(coverageStore_).mergeFrom(value).buildPartial();
        } else {
          coverageStore_ = value;
        }
        onChanged();
      } else {
        coverageStoreBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public Builder clearCoverageStore() {
      if (coverageStoreBuilder_ == null) {
        coverageStore_ = null;
        onChanged();
      } else {
        coverageStore_ = null;
        coverageStoreBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder getCoverageStoreBuilder() {
      
      onChanged();
      return getCoverageStoreFieldBuilder().getBuilder();
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    public ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder getCoverageStoreOrBuilder() {
      if (coverageStoreBuilder_ != null) {
        return coverageStoreBuilder_.getMessageOrBuilder();
      } else {
        return coverageStore_ == null ?
            ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.getDefaultInstance() : coverageStore_;
      }
    }
    /**
     * <code>.geoserver.CoverageStoreDetails.CoverageStore coverageStore = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder> 
        getCoverageStoreFieldBuilder() {
      if (coverageStoreBuilder_ == null) {
        coverageStoreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStore.Builder, ca.wise.geoserver.proto.CoverageStoreDetails.CoverageStoreOrBuilder>(
                getCoverageStore(),
                getParentForChildren(),
                isClean());
        coverageStore_ = null;
      }
      return coverageStoreBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geoserver.CoverageStoreDetails)
  }

  // @@protoc_insertion_point(class_scope:geoserver.CoverageStoreDetails)
  private static final ca.wise.geoserver.proto.CoverageStoreDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.geoserver.proto.CoverageStoreDetails();
  }

  public static ca.wise.geoserver.proto.CoverageStoreDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoverageStoreDetails>
      PARSER = new com.google.protobuf.AbstractParser<CoverageStoreDetails>() {
    @java.lang.Override
    public CoverageStoreDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CoverageStoreDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CoverageStoreDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoverageStoreDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.geoserver.proto.CoverageStoreDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

