// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

public final class GeoServer {
  private GeoServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListWorkspace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListWorkspace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListWorkspace_WorkspaceList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_NewWorkspace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_NewWorkspace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_NewWorkspace_WorkspaceName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_WorkspaceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_WorkspaceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_WorkspaceDetails_Workspace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_WorkspaceDetails_Workspace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListCoverageStore_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListCoverageStore_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListCoverageStore_CoverageStoreList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_CoverageStoreDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_ListCoverageStore_CoverageStoreList_CoverageStoreDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_NewCoverageStore_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_NewCoverageStore_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_NewCoverageStore_CoverageDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_NewCoverageStore_CoverageDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_CoverageStoreDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_CoverageStoreDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_CoverageStoreDetails_CoverageStore_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_CoverageWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_CoverageWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geoserver_CoverageWrapper_Coverage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geoserver_CoverageWrapper_Coverage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020geo_server.proto\022\tgeoserver\032\036google/pr" +
      "otobuf/wrappers.proto\"\331\001\n\rListWorkspace\022" +
      ":\n\nworkspaces\030\001 \001(\0132&.geoserver.ListWork" +
      "space.WorkspaceList\032\213\001\n\rWorkspaceList\022J\n" +
      "\tworkspace\030\001 \003(\01327.geoserver.ListWorkspa" +
      "ce.WorkspaceList.WorkspaceDetails\032.\n\020Wor" +
      "kspaceDetails\022\014\n\004name\030\001 \001(\t\022\014\n\004href\030\002 \001(" +
      "\t\"\224\001\n\014NewWorkspace\0228\n\tworkspace\030\001 \001(\0132%." +
      "geoserver.NewWorkspace.WorkspaceName\032J\n\r" +
      "WorkspaceName\022\014\n\004name\030\001 \001(\t\022+\n\007enabled\030\002" +
      " \001(\0132\032.google.protobuf.BoolValue\"\341\002\n\020Wor" +
      "kspaceDetails\0228\n\tworkspace\030\001 \001(\0132%.geose" +
      "rver.WorkspaceDetails.Workspace\032\222\002\n\tWork" +
      "space\022\014\n\004name\030\001 \001(\t\022,\n\010isolated\030\002 \001(\0132\032." +
      "google.protobuf.BoolValue\0220\n\ndataStores\030" +
      "\003 \001(\0132\034.google.protobuf.StringValue\0224\n\016c" +
      "overageStores\030\004 \001(\0132\034.google.protobuf.St" +
      "ringValue\022/\n\twmsStores\030\005 \001(\0132\034.google.pr" +
      "otobuf.StringValue\0220\n\nwmtsStores\030\006 \001(\0132\034" +
      ".google.protobuf.StringValue\"\201\002\n\021ListCov" +
      "erageStore\022F\n\016coverageStores\030\001 \001(\0132..geo" +
      "server.ListCoverageStore.CoverageStoreLi" +
      "st\032\243\001\n\021CoverageStoreList\022Z\n\rcoverageStor" +
      "e\030\001 \003(\0132C.geoserver.ListCoverageStore.Co" +
      "verageStoreList.CoverageStoreDetails\0322\n\024" +
      "CoverageStoreDetails\022\014\n\004name\030\001 \001(\t\022\014\n\004hr" +
      "ef\030\002 \001(\t\"\343\001\n\020NewCoverageStore\022B\n\rcoverag" +
      "eStore\030\001 \001(\0132+.geoserver.NewCoverageStor" +
      "e.CoverageDetails\032\212\001\n\017CoverageDetails\022\014\n" +
      "\004name\030\001 \001(\t\022\021\n\tworkspace\030\002 \001(\t\022)\n\003url\030\003 " +
      "\001(\0132\034.google.protobuf.StringValue\022+\n\007ena" +
      "bled\030\004 \001(\0132\032.google.protobuf.BoolValue\"\336" +
      "\003\n\024CoverageStoreDetails\022D\n\rcoverageStore" +
      "\030\001 \001(\0132-.geoserver.CoverageStoreDetails." +
      "CoverageStore\032\377\002\n\rCoverageStore\022\014\n\004name\030" +
      "\001 \001(\t\0221\n\013description\030\002 \001(\0132\034.google.prot" +
      "obuf.StringValue\022*\n\004type\030\003 \001(\0132\034.google." +
      "protobuf.StringValue\022+\n\007enabled\030\004 \001(\0132\032." +
      "google.protobuf.BoolValue\022J\n\tworkspace\030\005" +
      " \001(\01327.geoserver.ListWorkspace.Workspace" +
      "List.WorkspaceDetails\022,\n\010_default\030\006 \001(\0132" +
      "\032.google.protobuf.BoolValue\022)\n\003url\030\007 \001(\013" +
      "2\034.google.protobuf.StringValue\022/\n\tcovera" +
      "ges\030\010 \001(\0132\034.google.protobuf.StringValue\"" +
      "\200\001\n\017CoverageWrapper\0225\n\010coverage\030\001 \001(\0132#." +
      "geoserver.CoverageWrapper.Coverage\0326\n\010Co" +
      "verage\022\014\n\004name\030\001 \001(\t\022\013\n\003srs\030\002 \001(\t\022\017\n\007ena" +
      "bled\030\003 \001(\010B\033\n\027ca.wise.geoserver.protoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_geoserver_ListWorkspace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_geoserver_ListWorkspace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListWorkspace_descriptor,
        new java.lang.String[] { "Workspaces", });
    internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor =
      internal_static_geoserver_ListWorkspace_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_ListWorkspace_WorkspaceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor,
        new java.lang.String[] { "Workspace", });
    internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor =
      internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor,
        new java.lang.String[] { "Name", "Href", });
    internal_static_geoserver_NewWorkspace_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_geoserver_NewWorkspace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_NewWorkspace_descriptor,
        new java.lang.String[] { "Workspace", });
    internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor =
      internal_static_geoserver_NewWorkspace_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_NewWorkspace_WorkspaceName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor,
        new java.lang.String[] { "Name", "Enabled", });
    internal_static_geoserver_WorkspaceDetails_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_geoserver_WorkspaceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_WorkspaceDetails_descriptor,
        new java.lang.String[] { "Workspace", });
    internal_static_geoserver_WorkspaceDetails_Workspace_descriptor =
      internal_static_geoserver_WorkspaceDetails_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_WorkspaceDetails_Workspace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_WorkspaceDetails_Workspace_descriptor,
        new java.lang.String[] { "Name", "Isolated", "DataStores", "CoverageStores", "WmsStores", "WmtsStores", });
    internal_static_geoserver_ListCoverageStore_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_geoserver_ListCoverageStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListCoverageStore_descriptor,
        new java.lang.String[] { "CoverageStores", });
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_descriptor =
      internal_static_geoserver_ListCoverageStore_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListCoverageStore_CoverageStoreList_descriptor,
        new java.lang.String[] { "CoverageStore", });
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_CoverageStoreDetails_descriptor =
      internal_static_geoserver_ListCoverageStore_CoverageStoreList_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_ListCoverageStore_CoverageStoreList_CoverageStoreDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_ListCoverageStore_CoverageStoreList_CoverageStoreDetails_descriptor,
        new java.lang.String[] { "Name", "Href", });
    internal_static_geoserver_NewCoverageStore_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_geoserver_NewCoverageStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_NewCoverageStore_descriptor,
        new java.lang.String[] { "CoverageStore", });
    internal_static_geoserver_NewCoverageStore_CoverageDetails_descriptor =
      internal_static_geoserver_NewCoverageStore_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_NewCoverageStore_CoverageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_NewCoverageStore_CoverageDetails_descriptor,
        new java.lang.String[] { "Name", "Workspace", "Url", "Enabled", });
    internal_static_geoserver_CoverageStoreDetails_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_geoserver_CoverageStoreDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_CoverageStoreDetails_descriptor,
        new java.lang.String[] { "CoverageStore", });
    internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor =
      internal_static_geoserver_CoverageStoreDetails_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_CoverageStoreDetails_CoverageStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_CoverageStoreDetails_CoverageStore_descriptor,
        new java.lang.String[] { "Name", "Description", "Type", "Enabled", "Workspace", "Default", "Url", "Coverages", });
    internal_static_geoserver_CoverageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_geoserver_CoverageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_CoverageWrapper_descriptor,
        new java.lang.String[] { "Coverage", });
    internal_static_geoserver_CoverageWrapper_Coverage_descriptor =
      internal_static_geoserver_CoverageWrapper_descriptor.getNestedTypes().get(0);
    internal_static_geoserver_CoverageWrapper_Coverage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geoserver_CoverageWrapper_Coverage_descriptor,
        new java.lang.String[] { "Name", "Srs", "Enabled", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
