// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

/**
 * Protobuf type {@code geoserver.ListWorkspace}
 */
public final class ListWorkspace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geoserver.ListWorkspace)
    ListWorkspaceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListWorkspace.newBuilder() to construct.
  private ListWorkspace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListWorkspace() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListWorkspace();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListWorkspace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder subBuilder = null;
            if (workspaces_ != null) {
              subBuilder = workspaces_.toBuilder();
            }
            workspaces_ = input.readMessage(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(workspaces_);
              workspaces_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.geoserver.proto.ListWorkspace.class, ca.wise.geoserver.proto.ListWorkspace.Builder.class);
  }

  public interface WorkspaceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geoserver.ListWorkspace.WorkspaceList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> 
        getWorkspaceList();
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace(int index);
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    int getWorkspaceCount();
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    java.util.List<? extends ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> 
        getWorkspaceOrBuilderList();
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code geoserver.ListWorkspace.WorkspaceList}
   */
  public static final class WorkspaceList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geoserver.ListWorkspace.WorkspaceList)
      WorkspaceListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WorkspaceList.newBuilder() to construct.
    private WorkspaceList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WorkspaceList() {
      workspace_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WorkspaceList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WorkspaceList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                workspace_ = new java.util.ArrayList<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails>();
                mutable_bitField0_ |= 0x00000001;
              }
              workspace_.add(
                  input.readMessage(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          workspace_ = java.util.Collections.unmodifiableList(workspace_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.class, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder.class);
    }

    public interface WorkspaceDetailsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string href = 2;</code>
       * @return The href.
       */
      java.lang.String getHref();
      /**
       * <code>string href = 2;</code>
       * @return The bytes for href.
       */
      com.google.protobuf.ByteString
          getHrefBytes();
    }
    /**
     * Protobuf type {@code geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails}
     */
    public static final class WorkspaceDetails extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails)
        WorkspaceDetailsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use WorkspaceDetails.newBuilder() to construct.
      private WorkspaceDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private WorkspaceDetails() {
        name_ = "";
        href_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new WorkspaceDetails();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private WorkspaceDetails(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                href_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.class, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int HREF_FIELD_NUMBER = 2;
      private volatile java.lang.Object href_;
      /**
       * <code>string href = 2;</code>
       * @return The href.
       */
      @java.lang.Override
      public java.lang.String getHref() {
        java.lang.Object ref = href_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          href_ = s;
          return s;
        }
      }
      /**
       * <code>string href = 2;</code>
       * @return The bytes for href.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getHrefBytes() {
        java.lang.Object ref = href_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          href_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (!getHrefBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, href_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (!getHrefBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, href_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails)) {
          return super.equals(obj);
        }
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails other = (ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (!getHref()
            .equals(other.getHref())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + HREF_FIELD_NUMBER;
        hash = (53 * hash) + getHref().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails)
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.class, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder.class);
        }

        // Construct using ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          href_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_WorkspaceDetails_descriptor;
        }

        @java.lang.Override
        public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getDefaultInstanceForType() {
          return ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance();
        }

        @java.lang.Override
        public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails build() {
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails buildPartial() {
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails result = new ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails(this);
          result.name_ = name_;
          result.href_ = href_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails) {
            return mergeFrom((ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails other) {
          if (other == ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getHref().isEmpty()) {
            href_ = other.href_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object href_ = "";
        /**
         * <code>string href = 2;</code>
         * @return The href.
         */
        public java.lang.String getHref() {
          java.lang.Object ref = href_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            href_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string href = 2;</code>
         * @return The bytes for href.
         */
        public com.google.protobuf.ByteString
            getHrefBytes() {
          java.lang.Object ref = href_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            href_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string href = 2;</code>
         * @param value The href to set.
         * @return This builder for chaining.
         */
        public Builder setHref(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          href_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string href = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearHref() {
          
          href_ = getDefaultInstance().getHref();
          onChanged();
          return this;
        }
        /**
         * <code>string href = 2;</code>
         * @param value The bytes for href to set.
         * @return This builder for chaining.
         */
        public Builder setHrefBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          href_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails)
      }

      // @@protoc_insertion_point(class_scope:geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails)
      private static final ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails();
      }

      public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<WorkspaceDetails>
          PARSER = new com.google.protobuf.AbstractParser<WorkspaceDetails>() {
        @java.lang.Override
        public WorkspaceDetails parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new WorkspaceDetails(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<WorkspaceDetails> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<WorkspaceDetails> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int WORKSPACE_FIELD_NUMBER = 1;
    private java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> workspace_;
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> getWorkspaceList() {
      return workspace_;
    }
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> 
        getWorkspaceOrBuilderList() {
      return workspace_;
    }
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    @java.lang.Override
    public int getWorkspaceCount() {
      return workspace_.size();
    }
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace(int index) {
      return workspace_.get(index);
    }
    /**
     * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
     */
    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder(
        int index) {
      return workspace_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < workspace_.size(); i++) {
        output.writeMessage(1, workspace_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < workspace_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, workspace_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.geoserver.proto.ListWorkspace.WorkspaceList)) {
        return super.equals(obj);
      }
      ca.wise.geoserver.proto.ListWorkspace.WorkspaceList other = (ca.wise.geoserver.proto.ListWorkspace.WorkspaceList) obj;

      if (!getWorkspaceList()
          .equals(other.getWorkspaceList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWorkspaceCount() > 0) {
        hash = (37 * hash) + WORKSPACE_FIELD_NUMBER;
        hash = (53 * hash) + getWorkspaceList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geoserver.ListWorkspace.WorkspaceList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geoserver.ListWorkspace.WorkspaceList)
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.class, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder.class);
      }

      // Construct using ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWorkspaceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (workspaceBuilder_ == null) {
          workspace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          workspaceBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_WorkspaceList_descriptor;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList getDefaultInstanceForType() {
        return ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList build() {
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList buildPartial() {
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList result = new ca.wise.geoserver.proto.ListWorkspace.WorkspaceList(this);
        int from_bitField0_ = bitField0_;
        if (workspaceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            workspace_ = java.util.Collections.unmodifiableList(workspace_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.workspace_ = workspace_;
        } else {
          result.workspace_ = workspaceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.geoserver.proto.ListWorkspace.WorkspaceList) {
          return mergeFrom((ca.wise.geoserver.proto.ListWorkspace.WorkspaceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList other) {
        if (other == ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.getDefaultInstance()) return this;
        if (workspaceBuilder_ == null) {
          if (!other.workspace_.isEmpty()) {
            if (workspace_.isEmpty()) {
              workspace_ = other.workspace_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWorkspaceIsMutable();
              workspace_.addAll(other.workspace_);
            }
            onChanged();
          }
        } else {
          if (!other.workspace_.isEmpty()) {
            if (workspaceBuilder_.isEmpty()) {
              workspaceBuilder_.dispose();
              workspaceBuilder_ = null;
              workspace_ = other.workspace_;
              bitField0_ = (bitField0_ & ~0x00000001);
              workspaceBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWorkspaceFieldBuilder() : null;
            } else {
              workspaceBuilder_.addAllMessages(other.workspace_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.geoserver.proto.ListWorkspace.WorkspaceList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> workspace_ =
        java.util.Collections.emptyList();
      private void ensureWorkspaceIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          workspace_ = new java.util.ArrayList<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails>(workspace_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> workspaceBuilder_;

      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> getWorkspaceList() {
        if (workspaceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(workspace_);
        } else {
          return workspaceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public int getWorkspaceCount() {
        if (workspaceBuilder_ == null) {
          return workspace_.size();
        } else {
          return workspaceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails getWorkspace(int index) {
        if (workspaceBuilder_ == null) {
          return workspace_.get(index);
        } else {
          return workspaceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder setWorkspace(
          int index, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails value) {
        if (workspaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkspaceIsMutable();
          workspace_.set(index, value);
          onChanged();
        } else {
          workspaceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder setWorkspace(
          int index, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder builderForValue) {
        if (workspaceBuilder_ == null) {
          ensureWorkspaceIsMutable();
          workspace_.set(index, builderForValue.build());
          onChanged();
        } else {
          workspaceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder addWorkspace(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails value) {
        if (workspaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkspaceIsMutable();
          workspace_.add(value);
          onChanged();
        } else {
          workspaceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder addWorkspace(
          int index, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails value) {
        if (workspaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkspaceIsMutable();
          workspace_.add(index, value);
          onChanged();
        } else {
          workspaceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder addWorkspace(
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder builderForValue) {
        if (workspaceBuilder_ == null) {
          ensureWorkspaceIsMutable();
          workspace_.add(builderForValue.build());
          onChanged();
        } else {
          workspaceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder addWorkspace(
          int index, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder builderForValue) {
        if (workspaceBuilder_ == null) {
          ensureWorkspaceIsMutable();
          workspace_.add(index, builderForValue.build());
          onChanged();
        } else {
          workspaceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder addAllWorkspace(
          java.lang.Iterable<? extends ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails> values) {
        if (workspaceBuilder_ == null) {
          ensureWorkspaceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, workspace_);
          onChanged();
        } else {
          workspaceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder clearWorkspace() {
        if (workspaceBuilder_ == null) {
          workspace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          workspaceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public Builder removeWorkspace(int index) {
        if (workspaceBuilder_ == null) {
          ensureWorkspaceIsMutable();
          workspace_.remove(index);
          onChanged();
        } else {
          workspaceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder getWorkspaceBuilder(
          int index) {
        return getWorkspaceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder getWorkspaceOrBuilder(
          int index) {
        if (workspaceBuilder_ == null) {
          return workspace_.get(index);  } else {
          return workspaceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public java.util.List<? extends ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> 
           getWorkspaceOrBuilderList() {
        if (workspaceBuilder_ != null) {
          return workspaceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(workspace_);
        }
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder addWorkspaceBuilder() {
        return getWorkspaceFieldBuilder().addBuilder(
            ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder addWorkspaceBuilder(
          int index) {
        return getWorkspaceFieldBuilder().addBuilder(
            index, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .geoserver.ListWorkspace.WorkspaceList.WorkspaceDetails workspace = 1;</code>
       */
      public java.util.List<ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder> 
           getWorkspaceBuilderList() {
        return getWorkspaceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder> 
          getWorkspaceFieldBuilder() {
        if (workspaceBuilder_ == null) {
          workspaceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetails.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.WorkspaceDetailsOrBuilder>(
                  workspace_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          workspace_ = null;
        }
        return workspaceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geoserver.ListWorkspace.WorkspaceList)
    }

    // @@protoc_insertion_point(class_scope:geoserver.ListWorkspace.WorkspaceList)
    private static final ca.wise.geoserver.proto.ListWorkspace.WorkspaceList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.geoserver.proto.ListWorkspace.WorkspaceList();
    }

    public static ca.wise.geoserver.proto.ListWorkspace.WorkspaceList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WorkspaceList>
        PARSER = new com.google.protobuf.AbstractParser<WorkspaceList>() {
      @java.lang.Override
      public WorkspaceList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkspaceList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WorkspaceList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkspaceList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int WORKSPACES_FIELD_NUMBER = 1;
  private ca.wise.geoserver.proto.ListWorkspace.WorkspaceList workspaces_;
  /**
   * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
   * @return Whether the workspaces field is set.
   */
  @java.lang.Override
  public boolean hasWorkspaces() {
    return workspaces_ != null;
  }
  /**
   * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
   * @return The workspaces.
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList getWorkspaces() {
    return workspaces_ == null ? ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.getDefaultInstance() : workspaces_;
  }
  /**
   * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder getWorkspacesOrBuilder() {
    return getWorkspaces();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (workspaces_ != null) {
      output.writeMessage(1, getWorkspaces());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (workspaces_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWorkspaces());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.geoserver.proto.ListWorkspace)) {
      return super.equals(obj);
    }
    ca.wise.geoserver.proto.ListWorkspace other = (ca.wise.geoserver.proto.ListWorkspace) obj;

    if (hasWorkspaces() != other.hasWorkspaces()) return false;
    if (hasWorkspaces()) {
      if (!getWorkspaces()
          .equals(other.getWorkspaces())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorkspaces()) {
      hash = (37 * hash) + WORKSPACES_FIELD_NUMBER;
      hash = (53 * hash) + getWorkspaces().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.ListWorkspace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.geoserver.proto.ListWorkspace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geoserver.ListWorkspace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geoserver.ListWorkspace)
      ca.wise.geoserver.proto.ListWorkspaceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.ListWorkspace.class, ca.wise.geoserver.proto.ListWorkspace.Builder.class);
    }

    // Construct using ca.wise.geoserver.proto.ListWorkspace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (workspacesBuilder_ == null) {
        workspaces_ = null;
      } else {
        workspaces_ = null;
        workspacesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_ListWorkspace_descriptor;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace getDefaultInstanceForType() {
      return ca.wise.geoserver.proto.ListWorkspace.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace build() {
      ca.wise.geoserver.proto.ListWorkspace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.ListWorkspace buildPartial() {
      ca.wise.geoserver.proto.ListWorkspace result = new ca.wise.geoserver.proto.ListWorkspace(this);
      if (workspacesBuilder_ == null) {
        result.workspaces_ = workspaces_;
      } else {
        result.workspaces_ = workspacesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.geoserver.proto.ListWorkspace) {
        return mergeFrom((ca.wise.geoserver.proto.ListWorkspace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.geoserver.proto.ListWorkspace other) {
      if (other == ca.wise.geoserver.proto.ListWorkspace.getDefaultInstance()) return this;
      if (other.hasWorkspaces()) {
        mergeWorkspaces(other.getWorkspaces());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.geoserver.proto.ListWorkspace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.geoserver.proto.ListWorkspace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ca.wise.geoserver.proto.ListWorkspace.WorkspaceList workspaces_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder> workspacesBuilder_;
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     * @return Whether the workspaces field is set.
     */
    public boolean hasWorkspaces() {
      return workspacesBuilder_ != null || workspaces_ != null;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     * @return The workspaces.
     */
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList getWorkspaces() {
      if (workspacesBuilder_ == null) {
        return workspaces_ == null ? ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.getDefaultInstance() : workspaces_;
      } else {
        return workspacesBuilder_.getMessage();
      }
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public Builder setWorkspaces(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList value) {
      if (workspacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        workspaces_ = value;
        onChanged();
      } else {
        workspacesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public Builder setWorkspaces(
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder builderForValue) {
      if (workspacesBuilder_ == null) {
        workspaces_ = builderForValue.build();
        onChanged();
      } else {
        workspacesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public Builder mergeWorkspaces(ca.wise.geoserver.proto.ListWorkspace.WorkspaceList value) {
      if (workspacesBuilder_ == null) {
        if (workspaces_ != null) {
          workspaces_ =
            ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.newBuilder(workspaces_).mergeFrom(value).buildPartial();
        } else {
          workspaces_ = value;
        }
        onChanged();
      } else {
        workspacesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public Builder clearWorkspaces() {
      if (workspacesBuilder_ == null) {
        workspaces_ = null;
        onChanged();
      } else {
        workspaces_ = null;
        workspacesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder getWorkspacesBuilder() {
      
      onChanged();
      return getWorkspacesFieldBuilder().getBuilder();
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    public ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder getWorkspacesOrBuilder() {
      if (workspacesBuilder_ != null) {
        return workspacesBuilder_.getMessageOrBuilder();
      } else {
        return workspaces_ == null ?
            ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.getDefaultInstance() : workspaces_;
      }
    }
    /**
     * <code>.geoserver.ListWorkspace.WorkspaceList workspaces = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.ListWorkspace.WorkspaceList, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder> 
        getWorkspacesFieldBuilder() {
      if (workspacesBuilder_ == null) {
        workspacesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.geoserver.proto.ListWorkspace.WorkspaceList, ca.wise.geoserver.proto.ListWorkspace.WorkspaceList.Builder, ca.wise.geoserver.proto.ListWorkspace.WorkspaceListOrBuilder>(
                getWorkspaces(),
                getParentForChildren(),
                isClean());
        workspaces_ = null;
      }
      return workspacesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geoserver.ListWorkspace)
  }

  // @@protoc_insertion_point(class_scope:geoserver.ListWorkspace)
  private static final ca.wise.geoserver.proto.ListWorkspace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.geoserver.proto.ListWorkspace();
  }

  public static ca.wise.geoserver.proto.ListWorkspace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListWorkspace>
      PARSER = new com.google.protobuf.AbstractParser<ListWorkspace>() {
    @java.lang.Override
    public ListWorkspace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListWorkspace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListWorkspace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListWorkspace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.geoserver.proto.ListWorkspace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

