// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

public interface ListCoverageStoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoserver.ListCoverageStore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geoserver.ListCoverageStore.CoverageStoreList coverageStores = 1;</code>
   * @return Whether the coverageStores field is set.
   */
  boolean hasCoverageStores();
  /**
   * <code>.geoserver.ListCoverageStore.CoverageStoreList coverageStores = 1;</code>
   * @return The coverageStores.
   */
  ca.wise.geoserver.proto.ListCoverageStore.CoverageStoreList getCoverageStores();
  /**
   * <code>.geoserver.ListCoverageStore.CoverageStoreList coverageStores = 1;</code>
   */
  ca.wise.geoserver.proto.ListCoverageStore.CoverageStoreListOrBuilder getCoverageStoresOrBuilder();
}
