// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

public interface NewCoverageStoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoserver.NewCoverageStore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geoserver.NewCoverageStore.CoverageDetails coverageStore = 1;</code>
   * @return Whether the coverageStore field is set.
   */
  boolean hasCoverageStore();
  /**
   * <code>.geoserver.NewCoverageStore.CoverageDetails coverageStore = 1;</code>
   * @return The coverageStore.
   */
  ca.wise.geoserver.proto.NewCoverageStore.CoverageDetails getCoverageStore();
  /**
   * <code>.geoserver.NewCoverageStore.CoverageDetails coverageStore = 1;</code>
   */
  ca.wise.geoserver.proto.NewCoverageStore.CoverageDetailsOrBuilder getCoverageStoreOrBuilder();
}
