// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

/**
 * Protobuf type {@code geoserver.NewWorkspace}
 */
public final class NewWorkspace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geoserver.NewWorkspace)
    NewWorkspaceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewWorkspace.newBuilder() to construct.
  private NewWorkspace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewWorkspace() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NewWorkspace();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NewWorkspace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder subBuilder = null;
            if (workspace_ != null) {
              subBuilder = workspace_.toBuilder();
            }
            workspace_ = input.readMessage(ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(workspace_);
              workspace_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.geoserver.proto.NewWorkspace.class, ca.wise.geoserver.proto.NewWorkspace.Builder.class);
  }

  public interface WorkspaceNameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geoserver.NewWorkspace.WorkspaceName)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     * @return Whether the enabled field is set.
     */
    boolean hasEnabled();
    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     * @return The enabled.
     */
    com.google.protobuf.BoolValue getEnabled();
    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     */
    com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder();
  }
  /**
   * Protobuf type {@code geoserver.NewWorkspace.WorkspaceName}
   */
  public static final class WorkspaceName extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geoserver.NewWorkspace.WorkspaceName)
      WorkspaceNameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WorkspaceName.newBuilder() to construct.
    private WorkspaceName(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WorkspaceName() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WorkspaceName();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WorkspaceName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (enabled_ != null) {
                subBuilder = enabled_.toBuilder();
              }
              enabled_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enabled_);
                enabled_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_WorkspaceName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.class, ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENABLED_FIELD_NUMBER = 2;
    private com.google.protobuf.BoolValue enabled_;
    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     * @return Whether the enabled field is set.
     */
    @java.lang.Override
    public boolean hasEnabled() {
      return enabled_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public com.google.protobuf.BoolValue getEnabled() {
      return enabled_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
    }
    /**
     * <code>.google.protobuf.BoolValue enabled = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder() {
      return getEnabled();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (enabled_ != null) {
        output.writeMessage(2, getEnabled());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (enabled_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEnabled());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.geoserver.proto.NewWorkspace.WorkspaceName)) {
        return super.equals(obj);
      }
      ca.wise.geoserver.proto.NewWorkspace.WorkspaceName other = (ca.wise.geoserver.proto.NewWorkspace.WorkspaceName) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasEnabled() != other.hasEnabled()) return false;
      if (hasEnabled()) {
        if (!getEnabled()
            .equals(other.getEnabled())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasEnabled()) {
        hash = (37 * hash) + ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + getEnabled().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.geoserver.proto.NewWorkspace.WorkspaceName prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geoserver.NewWorkspace.WorkspaceName}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geoserver.NewWorkspace.WorkspaceName)
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_WorkspaceName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.class, ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder.class);
      }

      // Construct using ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (enabledBuilder_ == null) {
          enabled_ = null;
        } else {
          enabled_ = null;
          enabledBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_WorkspaceName_descriptor;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName getDefaultInstanceForType() {
        return ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName build() {
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName buildPartial() {
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName result = new ca.wise.geoserver.proto.NewWorkspace.WorkspaceName(this);
        result.name_ = name_;
        if (enabledBuilder_ == null) {
          result.enabled_ = enabled_;
        } else {
          result.enabled_ = enabledBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.geoserver.proto.NewWorkspace.WorkspaceName) {
          return mergeFrom((ca.wise.geoserver.proto.NewWorkspace.WorkspaceName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.geoserver.proto.NewWorkspace.WorkspaceName other) {
        if (other == ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEnabled()) {
          mergeEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.geoserver.proto.NewWorkspace.WorkspaceName) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.BoolValue enabled_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> enabledBuilder_;
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       * @return Whether the enabled field is set.
       */
      public boolean hasEnabled() {
        return enabledBuilder_ != null || enabled_ != null;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       * @return The enabled.
       */
      public com.google.protobuf.BoolValue getEnabled() {
        if (enabledBuilder_ == null) {
          return enabled_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
        } else {
          return enabledBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public Builder setEnabled(com.google.protobuf.BoolValue value) {
        if (enabledBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enabled_ = value;
          onChanged();
        } else {
          enabledBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public Builder setEnabled(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        if (enabledBuilder_ == null) {
          enabled_ = builderForValue.build();
          onChanged();
        } else {
          enabledBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public Builder mergeEnabled(com.google.protobuf.BoolValue value) {
        if (enabledBuilder_ == null) {
          if (enabled_ != null) {
            enabled_ =
              com.google.protobuf.BoolValue.newBuilder(enabled_).mergeFrom(value).buildPartial();
          } else {
            enabled_ = value;
          }
          onChanged();
        } else {
          enabledBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public Builder clearEnabled() {
        if (enabledBuilder_ == null) {
          enabled_ = null;
          onChanged();
        } else {
          enabled_ = null;
          enabledBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public com.google.protobuf.BoolValue.Builder getEnabledBuilder() {
        
        onChanged();
        return getEnabledFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      public com.google.protobuf.BoolValueOrBuilder getEnabledOrBuilder() {
        if (enabledBuilder_ != null) {
          return enabledBuilder_.getMessageOrBuilder();
        } else {
          return enabled_ == null ?
              com.google.protobuf.BoolValue.getDefaultInstance() : enabled_;
        }
      }
      /**
       * <code>.google.protobuf.BoolValue enabled = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
          getEnabledFieldBuilder() {
        if (enabledBuilder_ == null) {
          enabledBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                  getEnabled(),
                  getParentForChildren(),
                  isClean());
          enabled_ = null;
        }
        return enabledBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geoserver.NewWorkspace.WorkspaceName)
    }

    // @@protoc_insertion_point(class_scope:geoserver.NewWorkspace.WorkspaceName)
    private static final ca.wise.geoserver.proto.NewWorkspace.WorkspaceName DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.geoserver.proto.NewWorkspace.WorkspaceName();
    }

    public static ca.wise.geoserver.proto.NewWorkspace.WorkspaceName getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WorkspaceName>
        PARSER = new com.google.protobuf.AbstractParser<WorkspaceName>() {
      @java.lang.Override
      public WorkspaceName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkspaceName(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WorkspaceName> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkspaceName> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int WORKSPACE_FIELD_NUMBER = 1;
  private ca.wise.geoserver.proto.NewWorkspace.WorkspaceName workspace_;
  /**
   * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
   * @return Whether the workspace field is set.
   */
  @java.lang.Override
  public boolean hasWorkspace() {
    return workspace_ != null;
  }
  /**
   * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
   * @return The workspace.
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName getWorkspace() {
    return workspace_ == null ? ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.getDefaultInstance() : workspace_;
  }
  /**
   * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder getWorkspaceOrBuilder() {
    return getWorkspace();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (workspace_ != null) {
      output.writeMessage(1, getWorkspace());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (workspace_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWorkspace());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.geoserver.proto.NewWorkspace)) {
      return super.equals(obj);
    }
    ca.wise.geoserver.proto.NewWorkspace other = (ca.wise.geoserver.proto.NewWorkspace) obj;

    if (hasWorkspace() != other.hasWorkspace()) return false;
    if (hasWorkspace()) {
      if (!getWorkspace()
          .equals(other.getWorkspace())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorkspace()) {
      hash = (37 * hash) + WORKSPACE_FIELD_NUMBER;
      hash = (53 * hash) + getWorkspace().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.NewWorkspace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.geoserver.proto.NewWorkspace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geoserver.NewWorkspace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geoserver.NewWorkspace)
      ca.wise.geoserver.proto.NewWorkspaceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.NewWorkspace.class, ca.wise.geoserver.proto.NewWorkspace.Builder.class);
    }

    // Construct using ca.wise.geoserver.proto.NewWorkspace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (workspaceBuilder_ == null) {
        workspace_ = null;
      } else {
        workspace_ = null;
        workspaceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_NewWorkspace_descriptor;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.NewWorkspace getDefaultInstanceForType() {
      return ca.wise.geoserver.proto.NewWorkspace.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.NewWorkspace build() {
      ca.wise.geoserver.proto.NewWorkspace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.NewWorkspace buildPartial() {
      ca.wise.geoserver.proto.NewWorkspace result = new ca.wise.geoserver.proto.NewWorkspace(this);
      if (workspaceBuilder_ == null) {
        result.workspace_ = workspace_;
      } else {
        result.workspace_ = workspaceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.geoserver.proto.NewWorkspace) {
        return mergeFrom((ca.wise.geoserver.proto.NewWorkspace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.geoserver.proto.NewWorkspace other) {
      if (other == ca.wise.geoserver.proto.NewWorkspace.getDefaultInstance()) return this;
      if (other.hasWorkspace()) {
        mergeWorkspace(other.getWorkspace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.geoserver.proto.NewWorkspace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.geoserver.proto.NewWorkspace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ca.wise.geoserver.proto.NewWorkspace.WorkspaceName workspace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName, ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder, ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder> workspaceBuilder_;
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     * @return Whether the workspace field is set.
     */
    public boolean hasWorkspace() {
      return workspaceBuilder_ != null || workspace_ != null;
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     * @return The workspace.
     */
    public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName getWorkspace() {
      if (workspaceBuilder_ == null) {
        return workspace_ == null ? ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.getDefaultInstance() : workspace_;
      } else {
        return workspaceBuilder_.getMessage();
      }
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public Builder setWorkspace(ca.wise.geoserver.proto.NewWorkspace.WorkspaceName value) {
      if (workspaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        workspace_ = value;
        onChanged();
      } else {
        workspaceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public Builder setWorkspace(
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder builderForValue) {
      if (workspaceBuilder_ == null) {
        workspace_ = builderForValue.build();
        onChanged();
      } else {
        workspaceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public Builder mergeWorkspace(ca.wise.geoserver.proto.NewWorkspace.WorkspaceName value) {
      if (workspaceBuilder_ == null) {
        if (workspace_ != null) {
          workspace_ =
            ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.newBuilder(workspace_).mergeFrom(value).buildPartial();
        } else {
          workspace_ = value;
        }
        onChanged();
      } else {
        workspaceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public Builder clearWorkspace() {
      if (workspaceBuilder_ == null) {
        workspace_ = null;
        onChanged();
      } else {
        workspace_ = null;
        workspaceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder getWorkspaceBuilder() {
      
      onChanged();
      return getWorkspaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    public ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder getWorkspaceOrBuilder() {
      if (workspaceBuilder_ != null) {
        return workspaceBuilder_.getMessageOrBuilder();
      } else {
        return workspace_ == null ?
            ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.getDefaultInstance() : workspace_;
      }
    }
    /**
     * <code>.geoserver.NewWorkspace.WorkspaceName workspace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.NewWorkspace.WorkspaceName, ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder, ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder> 
        getWorkspaceFieldBuilder() {
      if (workspaceBuilder_ == null) {
        workspaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.geoserver.proto.NewWorkspace.WorkspaceName, ca.wise.geoserver.proto.NewWorkspace.WorkspaceName.Builder, ca.wise.geoserver.proto.NewWorkspace.WorkspaceNameOrBuilder>(
                getWorkspace(),
                getParentForChildren(),
                isClean());
        workspace_ = null;
      }
      return workspaceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geoserver.NewWorkspace)
  }

  // @@protoc_insertion_point(class_scope:geoserver.NewWorkspace)
  private static final ca.wise.geoserver.proto.NewWorkspace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.geoserver.proto.NewWorkspace();
  }

  public static ca.wise.geoserver.proto.NewWorkspace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewWorkspace>
      PARSER = new com.google.protobuf.AbstractParser<NewWorkspace>() {
    @java.lang.Override
    public NewWorkspace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NewWorkspace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NewWorkspace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewWorkspace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.geoserver.proto.NewWorkspace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

