// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

/**
 * Protobuf type {@code geoserver.WorkspaceDetails}
 */
public final class WorkspaceDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geoserver.WorkspaceDetails)
    WorkspaceDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkspaceDetails.newBuilder() to construct.
  private WorkspaceDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkspaceDetails() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkspaceDetails();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkspaceDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder subBuilder = null;
            if (workspace_ != null) {
              subBuilder = workspace_.toBuilder();
            }
            workspace_ = input.readMessage(ca.wise.geoserver.proto.WorkspaceDetails.Workspace.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(workspace_);
              workspace_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.geoserver.proto.WorkspaceDetails.class, ca.wise.geoserver.proto.WorkspaceDetails.Builder.class);
  }

  public interface WorkspaceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geoserver.WorkspaceDetails.Workspace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     * @return Whether the isolated field is set.
     */
    boolean hasIsolated();
    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     * @return The isolated.
     */
    com.google.protobuf.BoolValue getIsolated();
    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     */
    com.google.protobuf.BoolValueOrBuilder getIsolatedOrBuilder();

    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     * @return Whether the dataStores field is set.
     */
    boolean hasDataStores();
    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     * @return The dataStores.
     */
    com.google.protobuf.StringValue getDataStores();
    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getDataStoresOrBuilder();

    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     * @return Whether the coverageStores field is set.
     */
    boolean hasCoverageStores();
    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     * @return The coverageStores.
     */
    com.google.protobuf.StringValue getCoverageStores();
    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     */
    com.google.protobuf.StringValueOrBuilder getCoverageStoresOrBuilder();

    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     * @return Whether the wmsStores field is set.
     */
    boolean hasWmsStores();
    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     * @return The wmsStores.
     */
    com.google.protobuf.StringValue getWmsStores();
    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     */
    com.google.protobuf.StringValueOrBuilder getWmsStoresOrBuilder();

    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     * @return Whether the wmtsStores field is set.
     */
    boolean hasWmtsStores();
    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     * @return The wmtsStores.
     */
    com.google.protobuf.StringValue getWmtsStores();
    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     */
    com.google.protobuf.StringValueOrBuilder getWmtsStoresOrBuilder();
  }
  /**
   * Protobuf type {@code geoserver.WorkspaceDetails.Workspace}
   */
  public static final class Workspace extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geoserver.WorkspaceDetails.Workspace)
      WorkspaceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Workspace.newBuilder() to construct.
    private Workspace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Workspace() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Workspace();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Workspace(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (isolated_ != null) {
                subBuilder = isolated_.toBuilder();
              }
              isolated_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(isolated_);
                isolated_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (dataStores_ != null) {
                subBuilder = dataStores_.toBuilder();
              }
              dataStores_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dataStores_);
                dataStores_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (coverageStores_ != null) {
                subBuilder = coverageStores_.toBuilder();
              }
              coverageStores_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coverageStores_);
                coverageStores_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (wmsStores_ != null) {
                subBuilder = wmsStores_.toBuilder();
              }
              wmsStores_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wmsStores_);
                wmsStores_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (wmtsStores_ != null) {
                subBuilder = wmtsStores_.toBuilder();
              }
              wmtsStores_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wmtsStores_);
                wmtsStores_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_Workspace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_Workspace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.WorkspaceDetails.Workspace.class, ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISOLATED_FIELD_NUMBER = 2;
    private com.google.protobuf.BoolValue isolated_;
    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     * @return Whether the isolated field is set.
     */
    @java.lang.Override
    public boolean hasIsolated() {
      return isolated_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     * @return The isolated.
     */
    @java.lang.Override
    public com.google.protobuf.BoolValue getIsolated() {
      return isolated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : isolated_;
    }
    /**
     * <code>.google.protobuf.BoolValue isolated = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.BoolValueOrBuilder getIsolatedOrBuilder() {
      return getIsolated();
    }

    public static final int DATASTORES_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue dataStores_;
    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     * @return Whether the dataStores field is set.
     */
    @java.lang.Override
    public boolean hasDataStores() {
      return dataStores_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     * @return The dataStores.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getDataStores() {
      return dataStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dataStores_;
    }
    /**
     * <code>.google.protobuf.StringValue dataStores = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getDataStoresOrBuilder() {
      return getDataStores();
    }

    public static final int COVERAGESTORES_FIELD_NUMBER = 4;
    private com.google.protobuf.StringValue coverageStores_;
    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     * @return Whether the coverageStores field is set.
     */
    @java.lang.Override
    public boolean hasCoverageStores() {
      return coverageStores_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     * @return The coverageStores.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getCoverageStores() {
      return coverageStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : coverageStores_;
    }
    /**
     * <code>.google.protobuf.StringValue coverageStores = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getCoverageStoresOrBuilder() {
      return getCoverageStores();
    }

    public static final int WMSSTORES_FIELD_NUMBER = 5;
    private com.google.protobuf.StringValue wmsStores_;
    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     * @return Whether the wmsStores field is set.
     */
    @java.lang.Override
    public boolean hasWmsStores() {
      return wmsStores_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     * @return The wmsStores.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getWmsStores() {
      return wmsStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : wmsStores_;
    }
    /**
     * <code>.google.protobuf.StringValue wmsStores = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getWmsStoresOrBuilder() {
      return getWmsStores();
    }

    public static final int WMTSSTORES_FIELD_NUMBER = 6;
    private com.google.protobuf.StringValue wmtsStores_;
    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     * @return Whether the wmtsStores field is set.
     */
    @java.lang.Override
    public boolean hasWmtsStores() {
      return wmtsStores_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     * @return The wmtsStores.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getWmtsStores() {
      return wmtsStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : wmtsStores_;
    }
    /**
     * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getWmtsStoresOrBuilder() {
      return getWmtsStores();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (isolated_ != null) {
        output.writeMessage(2, getIsolated());
      }
      if (dataStores_ != null) {
        output.writeMessage(3, getDataStores());
      }
      if (coverageStores_ != null) {
        output.writeMessage(4, getCoverageStores());
      }
      if (wmsStores_ != null) {
        output.writeMessage(5, getWmsStores());
      }
      if (wmtsStores_ != null) {
        output.writeMessage(6, getWmtsStores());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (isolated_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIsolated());
      }
      if (dataStores_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDataStores());
      }
      if (coverageStores_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCoverageStores());
      }
      if (wmsStores_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getWmsStores());
      }
      if (wmtsStores_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getWmtsStores());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.geoserver.proto.WorkspaceDetails.Workspace)) {
        return super.equals(obj);
      }
      ca.wise.geoserver.proto.WorkspaceDetails.Workspace other = (ca.wise.geoserver.proto.WorkspaceDetails.Workspace) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasIsolated() != other.hasIsolated()) return false;
      if (hasIsolated()) {
        if (!getIsolated()
            .equals(other.getIsolated())) return false;
      }
      if (hasDataStores() != other.hasDataStores()) return false;
      if (hasDataStores()) {
        if (!getDataStores()
            .equals(other.getDataStores())) return false;
      }
      if (hasCoverageStores() != other.hasCoverageStores()) return false;
      if (hasCoverageStores()) {
        if (!getCoverageStores()
            .equals(other.getCoverageStores())) return false;
      }
      if (hasWmsStores() != other.hasWmsStores()) return false;
      if (hasWmsStores()) {
        if (!getWmsStores()
            .equals(other.getWmsStores())) return false;
      }
      if (hasWmtsStores() != other.hasWmtsStores()) return false;
      if (hasWmtsStores()) {
        if (!getWmtsStores()
            .equals(other.getWmtsStores())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasIsolated()) {
        hash = (37 * hash) + ISOLATED_FIELD_NUMBER;
        hash = (53 * hash) + getIsolated().hashCode();
      }
      if (hasDataStores()) {
        hash = (37 * hash) + DATASTORES_FIELD_NUMBER;
        hash = (53 * hash) + getDataStores().hashCode();
      }
      if (hasCoverageStores()) {
        hash = (37 * hash) + COVERAGESTORES_FIELD_NUMBER;
        hash = (53 * hash) + getCoverageStores().hashCode();
      }
      if (hasWmsStores()) {
        hash = (37 * hash) + WMSSTORES_FIELD_NUMBER;
        hash = (53 * hash) + getWmsStores().hashCode();
      }
      if (hasWmtsStores()) {
        hash = (37 * hash) + WMTSSTORES_FIELD_NUMBER;
        hash = (53 * hash) + getWmtsStores().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.geoserver.proto.WorkspaceDetails.Workspace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geoserver.WorkspaceDetails.Workspace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geoserver.WorkspaceDetails.Workspace)
        ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_Workspace_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_Workspace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.geoserver.proto.WorkspaceDetails.Workspace.class, ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder.class);
      }

      // Construct using ca.wise.geoserver.proto.WorkspaceDetails.Workspace.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (isolatedBuilder_ == null) {
          isolated_ = null;
        } else {
          isolated_ = null;
          isolatedBuilder_ = null;
        }
        if (dataStoresBuilder_ == null) {
          dataStores_ = null;
        } else {
          dataStores_ = null;
          dataStoresBuilder_ = null;
        }
        if (coverageStoresBuilder_ == null) {
          coverageStores_ = null;
        } else {
          coverageStores_ = null;
          coverageStoresBuilder_ = null;
        }
        if (wmsStoresBuilder_ == null) {
          wmsStores_ = null;
        } else {
          wmsStores_ = null;
          wmsStoresBuilder_ = null;
        }
        if (wmtsStoresBuilder_ == null) {
          wmtsStores_ = null;
        } else {
          wmtsStores_ = null;
          wmtsStoresBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_Workspace_descriptor;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.WorkspaceDetails.Workspace getDefaultInstanceForType() {
        return ca.wise.geoserver.proto.WorkspaceDetails.Workspace.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.WorkspaceDetails.Workspace build() {
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.geoserver.proto.WorkspaceDetails.Workspace buildPartial() {
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace result = new ca.wise.geoserver.proto.WorkspaceDetails.Workspace(this);
        result.name_ = name_;
        if (isolatedBuilder_ == null) {
          result.isolated_ = isolated_;
        } else {
          result.isolated_ = isolatedBuilder_.build();
        }
        if (dataStoresBuilder_ == null) {
          result.dataStores_ = dataStores_;
        } else {
          result.dataStores_ = dataStoresBuilder_.build();
        }
        if (coverageStoresBuilder_ == null) {
          result.coverageStores_ = coverageStores_;
        } else {
          result.coverageStores_ = coverageStoresBuilder_.build();
        }
        if (wmsStoresBuilder_ == null) {
          result.wmsStores_ = wmsStores_;
        } else {
          result.wmsStores_ = wmsStoresBuilder_.build();
        }
        if (wmtsStoresBuilder_ == null) {
          result.wmtsStores_ = wmtsStores_;
        } else {
          result.wmtsStores_ = wmtsStoresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.geoserver.proto.WorkspaceDetails.Workspace) {
          return mergeFrom((ca.wise.geoserver.proto.WorkspaceDetails.Workspace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.geoserver.proto.WorkspaceDetails.Workspace other) {
        if (other == ca.wise.geoserver.proto.WorkspaceDetails.Workspace.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasIsolated()) {
          mergeIsolated(other.getIsolated());
        }
        if (other.hasDataStores()) {
          mergeDataStores(other.getDataStores());
        }
        if (other.hasCoverageStores()) {
          mergeCoverageStores(other.getCoverageStores());
        }
        if (other.hasWmsStores()) {
          mergeWmsStores(other.getWmsStores());
        }
        if (other.hasWmtsStores()) {
          mergeWmtsStores(other.getWmtsStores());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.geoserver.proto.WorkspaceDetails.Workspace) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.BoolValue isolated_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> isolatedBuilder_;
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       * @return Whether the isolated field is set.
       */
      public boolean hasIsolated() {
        return isolatedBuilder_ != null || isolated_ != null;
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       * @return The isolated.
       */
      public com.google.protobuf.BoolValue getIsolated() {
        if (isolatedBuilder_ == null) {
          return isolated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : isolated_;
        } else {
          return isolatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public Builder setIsolated(com.google.protobuf.BoolValue value) {
        if (isolatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          isolated_ = value;
          onChanged();
        } else {
          isolatedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public Builder setIsolated(
          com.google.protobuf.BoolValue.Builder builderForValue) {
        if (isolatedBuilder_ == null) {
          isolated_ = builderForValue.build();
          onChanged();
        } else {
          isolatedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public Builder mergeIsolated(com.google.protobuf.BoolValue value) {
        if (isolatedBuilder_ == null) {
          if (isolated_ != null) {
            isolated_ =
              com.google.protobuf.BoolValue.newBuilder(isolated_).mergeFrom(value).buildPartial();
          } else {
            isolated_ = value;
          }
          onChanged();
        } else {
          isolatedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public Builder clearIsolated() {
        if (isolatedBuilder_ == null) {
          isolated_ = null;
          onChanged();
        } else {
          isolated_ = null;
          isolatedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public com.google.protobuf.BoolValue.Builder getIsolatedBuilder() {
        
        onChanged();
        return getIsolatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      public com.google.protobuf.BoolValueOrBuilder getIsolatedOrBuilder() {
        if (isolatedBuilder_ != null) {
          return isolatedBuilder_.getMessageOrBuilder();
        } else {
          return isolated_ == null ?
              com.google.protobuf.BoolValue.getDefaultInstance() : isolated_;
        }
      }
      /**
       * <code>.google.protobuf.BoolValue isolated = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
          getIsolatedFieldBuilder() {
        if (isolatedBuilder_ == null) {
          isolatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                  getIsolated(),
                  getParentForChildren(),
                  isClean());
          isolated_ = null;
        }
        return isolatedBuilder_;
      }

      private com.google.protobuf.StringValue dataStores_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> dataStoresBuilder_;
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       * @return Whether the dataStores field is set.
       */
      public boolean hasDataStores() {
        return dataStoresBuilder_ != null || dataStores_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       * @return The dataStores.
       */
      public com.google.protobuf.StringValue getDataStores() {
        if (dataStoresBuilder_ == null) {
          return dataStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dataStores_;
        } else {
          return dataStoresBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public Builder setDataStores(com.google.protobuf.StringValue value) {
        if (dataStoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataStores_ = value;
          onChanged();
        } else {
          dataStoresBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public Builder setDataStores(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (dataStoresBuilder_ == null) {
          dataStores_ = builderForValue.build();
          onChanged();
        } else {
          dataStoresBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public Builder mergeDataStores(com.google.protobuf.StringValue value) {
        if (dataStoresBuilder_ == null) {
          if (dataStores_ != null) {
            dataStores_ =
              com.google.protobuf.StringValue.newBuilder(dataStores_).mergeFrom(value).buildPartial();
          } else {
            dataStores_ = value;
          }
          onChanged();
        } else {
          dataStoresBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public Builder clearDataStores() {
        if (dataStoresBuilder_ == null) {
          dataStores_ = null;
          onChanged();
        } else {
          dataStores_ = null;
          dataStoresBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getDataStoresBuilder() {
        
        onChanged();
        return getDataStoresFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getDataStoresOrBuilder() {
        if (dataStoresBuilder_ != null) {
          return dataStoresBuilder_.getMessageOrBuilder();
        } else {
          return dataStores_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : dataStores_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue dataStores = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getDataStoresFieldBuilder() {
        if (dataStoresBuilder_ == null) {
          dataStoresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getDataStores(),
                  getParentForChildren(),
                  isClean());
          dataStores_ = null;
        }
        return dataStoresBuilder_;
      }

      private com.google.protobuf.StringValue coverageStores_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> coverageStoresBuilder_;
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       * @return Whether the coverageStores field is set.
       */
      public boolean hasCoverageStores() {
        return coverageStoresBuilder_ != null || coverageStores_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       * @return The coverageStores.
       */
      public com.google.protobuf.StringValue getCoverageStores() {
        if (coverageStoresBuilder_ == null) {
          return coverageStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : coverageStores_;
        } else {
          return coverageStoresBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public Builder setCoverageStores(com.google.protobuf.StringValue value) {
        if (coverageStoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coverageStores_ = value;
          onChanged();
        } else {
          coverageStoresBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public Builder setCoverageStores(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (coverageStoresBuilder_ == null) {
          coverageStores_ = builderForValue.build();
          onChanged();
        } else {
          coverageStoresBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public Builder mergeCoverageStores(com.google.protobuf.StringValue value) {
        if (coverageStoresBuilder_ == null) {
          if (coverageStores_ != null) {
            coverageStores_ =
              com.google.protobuf.StringValue.newBuilder(coverageStores_).mergeFrom(value).buildPartial();
          } else {
            coverageStores_ = value;
          }
          onChanged();
        } else {
          coverageStoresBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public Builder clearCoverageStores() {
        if (coverageStoresBuilder_ == null) {
          coverageStores_ = null;
          onChanged();
        } else {
          coverageStores_ = null;
          coverageStoresBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public com.google.protobuf.StringValue.Builder getCoverageStoresBuilder() {
        
        onChanged();
        return getCoverageStoresFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getCoverageStoresOrBuilder() {
        if (coverageStoresBuilder_ != null) {
          return coverageStoresBuilder_.getMessageOrBuilder();
        } else {
          return coverageStores_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : coverageStores_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue coverageStores = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getCoverageStoresFieldBuilder() {
        if (coverageStoresBuilder_ == null) {
          coverageStoresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getCoverageStores(),
                  getParentForChildren(),
                  isClean());
          coverageStores_ = null;
        }
        return coverageStoresBuilder_;
      }

      private com.google.protobuf.StringValue wmsStores_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> wmsStoresBuilder_;
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       * @return Whether the wmsStores field is set.
       */
      public boolean hasWmsStores() {
        return wmsStoresBuilder_ != null || wmsStores_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       * @return The wmsStores.
       */
      public com.google.protobuf.StringValue getWmsStores() {
        if (wmsStoresBuilder_ == null) {
          return wmsStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : wmsStores_;
        } else {
          return wmsStoresBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public Builder setWmsStores(com.google.protobuf.StringValue value) {
        if (wmsStoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wmsStores_ = value;
          onChanged();
        } else {
          wmsStoresBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public Builder setWmsStores(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (wmsStoresBuilder_ == null) {
          wmsStores_ = builderForValue.build();
          onChanged();
        } else {
          wmsStoresBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public Builder mergeWmsStores(com.google.protobuf.StringValue value) {
        if (wmsStoresBuilder_ == null) {
          if (wmsStores_ != null) {
            wmsStores_ =
              com.google.protobuf.StringValue.newBuilder(wmsStores_).mergeFrom(value).buildPartial();
          } else {
            wmsStores_ = value;
          }
          onChanged();
        } else {
          wmsStoresBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public Builder clearWmsStores() {
        if (wmsStoresBuilder_ == null) {
          wmsStores_ = null;
          onChanged();
        } else {
          wmsStores_ = null;
          wmsStoresBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public com.google.protobuf.StringValue.Builder getWmsStoresBuilder() {
        
        onChanged();
        return getWmsStoresFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getWmsStoresOrBuilder() {
        if (wmsStoresBuilder_ != null) {
          return wmsStoresBuilder_.getMessageOrBuilder();
        } else {
          return wmsStores_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : wmsStores_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue wmsStores = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getWmsStoresFieldBuilder() {
        if (wmsStoresBuilder_ == null) {
          wmsStoresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getWmsStores(),
                  getParentForChildren(),
                  isClean());
          wmsStores_ = null;
        }
        return wmsStoresBuilder_;
      }

      private com.google.protobuf.StringValue wmtsStores_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> wmtsStoresBuilder_;
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       * @return Whether the wmtsStores field is set.
       */
      public boolean hasWmtsStores() {
        return wmtsStoresBuilder_ != null || wmtsStores_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       * @return The wmtsStores.
       */
      public com.google.protobuf.StringValue getWmtsStores() {
        if (wmtsStoresBuilder_ == null) {
          return wmtsStores_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : wmtsStores_;
        } else {
          return wmtsStoresBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public Builder setWmtsStores(com.google.protobuf.StringValue value) {
        if (wmtsStoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wmtsStores_ = value;
          onChanged();
        } else {
          wmtsStoresBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public Builder setWmtsStores(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (wmtsStoresBuilder_ == null) {
          wmtsStores_ = builderForValue.build();
          onChanged();
        } else {
          wmtsStoresBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public Builder mergeWmtsStores(com.google.protobuf.StringValue value) {
        if (wmtsStoresBuilder_ == null) {
          if (wmtsStores_ != null) {
            wmtsStores_ =
              com.google.protobuf.StringValue.newBuilder(wmtsStores_).mergeFrom(value).buildPartial();
          } else {
            wmtsStores_ = value;
          }
          onChanged();
        } else {
          wmtsStoresBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public Builder clearWmtsStores() {
        if (wmtsStoresBuilder_ == null) {
          wmtsStores_ = null;
          onChanged();
        } else {
          wmtsStores_ = null;
          wmtsStoresBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public com.google.protobuf.StringValue.Builder getWmtsStoresBuilder() {
        
        onChanged();
        return getWmtsStoresFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getWmtsStoresOrBuilder() {
        if (wmtsStoresBuilder_ != null) {
          return wmtsStoresBuilder_.getMessageOrBuilder();
        } else {
          return wmtsStores_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : wmtsStores_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue wmtsStores = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getWmtsStoresFieldBuilder() {
        if (wmtsStoresBuilder_ == null) {
          wmtsStoresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getWmtsStores(),
                  getParentForChildren(),
                  isClean());
          wmtsStores_ = null;
        }
        return wmtsStoresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geoserver.WorkspaceDetails.Workspace)
    }

    // @@protoc_insertion_point(class_scope:geoserver.WorkspaceDetails.Workspace)
    private static final ca.wise.geoserver.proto.WorkspaceDetails.Workspace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.geoserver.proto.WorkspaceDetails.Workspace();
    }

    public static ca.wise.geoserver.proto.WorkspaceDetails.Workspace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Workspace>
        PARSER = new com.google.protobuf.AbstractParser<Workspace>() {
      @java.lang.Override
      public Workspace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Workspace(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Workspace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Workspace> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.WorkspaceDetails.Workspace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int WORKSPACE_FIELD_NUMBER = 1;
  private ca.wise.geoserver.proto.WorkspaceDetails.Workspace workspace_;
  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   * @return Whether the workspace field is set.
   */
  @java.lang.Override
  public boolean hasWorkspace() {
    return workspace_ != null;
  }
  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   * @return The workspace.
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.WorkspaceDetails.Workspace getWorkspace() {
    return workspace_ == null ? ca.wise.geoserver.proto.WorkspaceDetails.Workspace.getDefaultInstance() : workspace_;
  }
  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   */
  @java.lang.Override
  public ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder getWorkspaceOrBuilder() {
    return getWorkspace();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (workspace_ != null) {
      output.writeMessage(1, getWorkspace());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (workspace_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWorkspace());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.geoserver.proto.WorkspaceDetails)) {
      return super.equals(obj);
    }
    ca.wise.geoserver.proto.WorkspaceDetails other = (ca.wise.geoserver.proto.WorkspaceDetails) obj;

    if (hasWorkspace() != other.hasWorkspace()) return false;
    if (hasWorkspace()) {
      if (!getWorkspace()
          .equals(other.getWorkspace())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorkspace()) {
      hash = (37 * hash) + WORKSPACE_FIELD_NUMBER;
      hash = (53 * hash) + getWorkspace().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.geoserver.proto.WorkspaceDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.geoserver.proto.WorkspaceDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geoserver.WorkspaceDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geoserver.WorkspaceDetails)
      ca.wise.geoserver.proto.WorkspaceDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.geoserver.proto.WorkspaceDetails.class, ca.wise.geoserver.proto.WorkspaceDetails.Builder.class);
    }

    // Construct using ca.wise.geoserver.proto.WorkspaceDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (workspaceBuilder_ == null) {
        workspace_ = null;
      } else {
        workspace_ = null;
        workspaceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.geoserver.proto.GeoServer.internal_static_geoserver_WorkspaceDetails_descriptor;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.WorkspaceDetails getDefaultInstanceForType() {
      return ca.wise.geoserver.proto.WorkspaceDetails.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.WorkspaceDetails build() {
      ca.wise.geoserver.proto.WorkspaceDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.geoserver.proto.WorkspaceDetails buildPartial() {
      ca.wise.geoserver.proto.WorkspaceDetails result = new ca.wise.geoserver.proto.WorkspaceDetails(this);
      if (workspaceBuilder_ == null) {
        result.workspace_ = workspace_;
      } else {
        result.workspace_ = workspaceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.geoserver.proto.WorkspaceDetails) {
        return mergeFrom((ca.wise.geoserver.proto.WorkspaceDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.geoserver.proto.WorkspaceDetails other) {
      if (other == ca.wise.geoserver.proto.WorkspaceDetails.getDefaultInstance()) return this;
      if (other.hasWorkspace()) {
        mergeWorkspace(other.getWorkspace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.geoserver.proto.WorkspaceDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.geoserver.proto.WorkspaceDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ca.wise.geoserver.proto.WorkspaceDetails.Workspace workspace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace, ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder, ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder> workspaceBuilder_;
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     * @return Whether the workspace field is set.
     */
    public boolean hasWorkspace() {
      return workspaceBuilder_ != null || workspace_ != null;
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     * @return The workspace.
     */
    public ca.wise.geoserver.proto.WorkspaceDetails.Workspace getWorkspace() {
      if (workspaceBuilder_ == null) {
        return workspace_ == null ? ca.wise.geoserver.proto.WorkspaceDetails.Workspace.getDefaultInstance() : workspace_;
      } else {
        return workspaceBuilder_.getMessage();
      }
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public Builder setWorkspace(ca.wise.geoserver.proto.WorkspaceDetails.Workspace value) {
      if (workspaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        workspace_ = value;
        onChanged();
      } else {
        workspaceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public Builder setWorkspace(
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder builderForValue) {
      if (workspaceBuilder_ == null) {
        workspace_ = builderForValue.build();
        onChanged();
      } else {
        workspaceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public Builder mergeWorkspace(ca.wise.geoserver.proto.WorkspaceDetails.Workspace value) {
      if (workspaceBuilder_ == null) {
        if (workspace_ != null) {
          workspace_ =
            ca.wise.geoserver.proto.WorkspaceDetails.Workspace.newBuilder(workspace_).mergeFrom(value).buildPartial();
        } else {
          workspace_ = value;
        }
        onChanged();
      } else {
        workspaceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public Builder clearWorkspace() {
      if (workspaceBuilder_ == null) {
        workspace_ = null;
        onChanged();
      } else {
        workspace_ = null;
        workspaceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder getWorkspaceBuilder() {
      
      onChanged();
      return getWorkspaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    public ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder getWorkspaceOrBuilder() {
      if (workspaceBuilder_ != null) {
        return workspaceBuilder_.getMessageOrBuilder();
      } else {
        return workspace_ == null ?
            ca.wise.geoserver.proto.WorkspaceDetails.Workspace.getDefaultInstance() : workspace_;
      }
    }
    /**
     * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.geoserver.proto.WorkspaceDetails.Workspace, ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder, ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder> 
        getWorkspaceFieldBuilder() {
      if (workspaceBuilder_ == null) {
        workspaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.geoserver.proto.WorkspaceDetails.Workspace, ca.wise.geoserver.proto.WorkspaceDetails.Workspace.Builder, ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder>(
                getWorkspace(),
                getParentForChildren(),
                isClean());
        workspace_ = null;
      }
      return workspaceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geoserver.WorkspaceDetails)
  }

  // @@protoc_insertion_point(class_scope:geoserver.WorkspaceDetails)
  private static final ca.wise.geoserver.proto.WorkspaceDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.geoserver.proto.WorkspaceDetails();
  }

  public static ca.wise.geoserver.proto.WorkspaceDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkspaceDetails>
      PARSER = new com.google.protobuf.AbstractParser<WorkspaceDetails>() {
    @java.lang.Override
    public WorkspaceDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkspaceDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkspaceDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkspaceDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.geoserver.proto.WorkspaceDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

