// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo_server.proto

package ca.wise.geoserver.proto;

public interface WorkspaceDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoserver.WorkspaceDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   * @return Whether the workspace field is set.
   */
  boolean hasWorkspace();
  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   * @return The workspace.
   */
  ca.wise.geoserver.proto.WorkspaceDetails.Workspace getWorkspace();
  /**
   * <code>.geoserver.WorkspaceDetails.Workspace workspace = 1;</code>
   */
  ca.wise.geoserver.proto.WorkspaceDetails.WorkspaceOrBuilder getWorkspaceOrBuilder();
}
