// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager_settings.proto

package ca.wise.settings.proto;

public interface ManagerSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.settings.ManagerSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The job storage directory
   * </pre>
   *
   * <code>string jobDirectory = 3;</code>
   * @return The jobDirectory.
   */
  java.lang.String getJobDirectory();
  /**
   * <pre>
   *The job storage directory
   * </pre>
   *
   * <code>string jobDirectory = 3;</code>
   * @return The bytes for jobDirectory.
   */
  com.google.protobuf.ByteString
      getJobDirectoryBytes();

  /**
   * <pre>
   *The last time that this file was updated
   * </pre>
   *
   * <code>.google.protobuf.Timestamp lastUpdate = 11;</code>
   * @return Whether the lastUpdate field is set.
   */
  boolean hasLastUpdate();
  /**
   * <pre>
   *The last time that this file was updated
   * </pre>
   *
   * <code>.google.protobuf.Timestamp lastUpdate = 11;</code>
   * @return The lastUpdate.
   */
  com.google.protobuf.Timestamp getLastUpdate();
  /**
   * <pre>
   *The last time that this file was updated
   * </pre>
   *
   * <code>.google.protobuf.Timestamp lastUpdate = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdateOrBuilder();
}
